//
// Created by joaquin on 17/11/25.
//

#ifndef TALLER_DE_PROGRAMACION_TP_GRUPAL_2025C2_GRUPO_2_MINIMALSDL_H
#define TALLER_DE_PROGRAMACION_TP_GRUPAL_2025C2_GRUPO_2_MINIMALSDL_H


class MinimalSdl {};


#endif  // TALLER_DE_PROGRAMACION_TP_GRUPAL_2025C2_GRUPO_2_MINIMALSDL_H
