

#ifndef TALLER_DE_PROGRAMACION_TP_GRUPAL_2025C2_GRUPO_2_MINIMALQT_H
#define TALLER_DE_PROGRAMACION_TP_GRUPAL_2025C2_GRUPO_2_MINIMALQT_H


class MinimalQt {};


#endif  // TALLER_DE_PROGRAMACION_TP_GRUPAL_2025C2_GRUPO_2_MINIMALQT_H
